// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_120ibmtXpnWbOBXf3y13v_HPl0UuISI',
    appId: '1:749355270093:web:e1cdffc49dd2e999a80e84',
    messagingSenderId: '749355270093',
    projectId: 'packare',
    authDomain: 'packare.firebaseapp.com',
    storageBucket: 'packare.appspot.com',
    measurementId: 'G-J97MFZ8WST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcfp86qLZAAwBtoo2SNKon1GmNkBUo1OM',
    appId: '1:749355270093:android:65a1798ad78ffabda80e84',
    messagingSenderId: '749355270093',
    projectId: 'packare',
    storageBucket: 'packare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA45JTBO5d9xiyW0Iljm3AzK1w2phJTeeE',
    appId: '1:749355270093:ios:73d2095eb3aaea2fa80e84',
    messagingSenderId: '749355270093',
    projectId: 'packare',
    storageBucket: 'packare.appspot.com',
    iosBundleId: 'com.example.packare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA45JTBO5d9xiyW0Iljm3AzK1w2phJTeeE',
    appId: '1:749355270093:ios:42ec8ccc0ff04ce3a80e84',
    messagingSenderId: '749355270093',
    projectId: 'packare',
    storageBucket: 'packare.appspot.com',
    iosBundleId: 'com.example.packare.RunnerTests',
  );
}
